name: "Pipeline DEV"

on:
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws-region: "us-east-1"
      aws-state-s3-bucket: "aws-prd-state-mack-iac-pipeline"
      aws-lock-table: "aws-mack-dyn-github-lock-table"
      aws-assume-role-arn: "arn:aws:iam::211125430322:role/aws-mack-role-github-actions-giovanni"